//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIS.ADO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Data.Entity.Core.Objects.DataClasses;
    using System.Linq;
    
    public partial class A_ZULIA_12Entities : DbContext
    {
        public A_ZULIA_12Entities()
            : base("name=A_ZULIA_12Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Usuarios> Usuarios { get; set; }
        public DbSet<ZCotizacionRengNB> ZCotizacionRengNB { get; set; }
        public DbSet<ZCotizacionNB> ZCotizacionNB { get; set; }
    
        public virtual ObjectResult<buscarPorDocumCC_Result> buscarPorDocumCC(string consulta, Nullable<int> cantidad, string usuario)
        {
            var consultaParameter = consulta != null ?
                new ObjectParameter("consulta", consulta) :
                new ObjectParameter("consulta", typeof(string));
    
            var cantidadParameter = cantidad.HasValue ?
                new ObjectParameter("cantidad", cantidad) :
                new ObjectParameter("cantidad", typeof(int));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<buscarPorDocumCC_Result>("buscarPorDocumCC", consultaParameter, cantidadParameter, usuarioParameter);
        }
    
        public virtual ObjectResult<buscarPorDocumCC1_Result> buscarPorDocumCC1(string consulta, Nullable<int> cantidad, string usuario)
        {
            var consultaParameter = consulta != null ?
                new ObjectParameter("consulta", consulta) :
                new ObjectParameter("consulta", typeof(string));
    
            var cantidadParameter = cantidad.HasValue ?
                new ObjectParameter("cantidad", cantidad) :
                new ObjectParameter("cantidad", typeof(int));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<buscarPorDocumCC1_Result>("buscarPorDocumCC1", consultaParameter, cantidadParameter, usuarioParameter);
        }
    
        public virtual ObjectResult<buscarPorDocumCC11_Result> buscarPorDocumCC11(string consulta, Nullable<int> cantidad, string usuario)
        {
            var consultaParameter = consulta != null ?
                new ObjectParameter("consulta", consulta) :
                new ObjectParameter("consulta", typeof(string));
    
            var cantidadParameter = cantidad.HasValue ?
                new ObjectParameter("cantidad", cantidad) :
                new ObjectParameter("cantidad", typeof(int));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<buscarPorDocumCC11_Result>("buscarPorDocumCC11", consultaParameter, cantidadParameter, usuarioParameter);
        }
    
        public virtual ObjectResult<buscarPrecios_Result> buscarPrecios(string busqueda)
        {
            var busquedaParameter = busqueda != null ?
                new ObjectParameter("busqueda", busqueda) :
                new ObjectParameter("busqueda", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<buscarPrecios_Result>("buscarPrecios", busquedaParameter);
        }
    
        public virtual ObjectResult<buscarPorDocumCP_Result> buscarPorDocumCP(string consulta, Nullable<int> cantidad, string usuario)
        {
            var consultaParameter = consulta != null ?
                new ObjectParameter("consulta", consulta) :
                new ObjectParameter("consulta", typeof(string));
    
            var cantidadParameter = cantidad.HasValue ?
                new ObjectParameter("cantidad", cantidad) :
                new ObjectParameter("cantidad", typeof(int));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<buscarPorDocumCP_Result>("buscarPorDocumCP", consultaParameter, cantidadParameter, usuarioParameter);
        }
    
        public virtual ObjectResult<BuscarCliente_Result> BuscarCliente(string consulta)
        {
            var consultaParameter = consulta != null ?
                new ObjectParameter("consulta", consulta) :
                new ObjectParameter("consulta", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BuscarCliente_Result>("BuscarCliente", consultaParameter);
        }
    
        public virtual ObjectResult<BuscarTransporte_Result> BuscarTransporte(string consulta)
        {
            var consultaParameter = consulta != null ?
                new ObjectParameter("consulta", consulta) :
                new ObjectParameter("consulta", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BuscarTransporte_Result>("BuscarTransporte", consultaParameter);
        }
    
        public virtual ObjectResult<buscarCliente1_Result> buscarCliente1(string consulta)
        {
            var consultaParameter = consulta != null ?
                new ObjectParameter("consulta", consulta) :
                new ObjectParameter("consulta", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<buscarCliente1_Result>("buscarCliente1", consultaParameter);
        }
    
        public virtual ObjectResult<buscarPrecios1_Result> buscarPrecios1(string busqueda)
        {
            var busquedaParameter = busqueda != null ?
                new ObjectParameter("busqueda", busqueda) :
                new ObjectParameter("busqueda", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<buscarPrecios1_Result>("buscarPrecios1", busquedaParameter);
        }
    
        public virtual ObjectResult<buscarVendedor_Result> buscarVendedor(string consulta)
        {
            var consultaParameter = consulta != null ?
                new ObjectParameter("consulta", consulta) :
                new ObjectParameter("consulta", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<buscarVendedor_Result>("buscarVendedor", consultaParameter);
        }
    
        public virtual ObjectResult<buscarTransporte1_Result> buscarTransporte1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<buscarTransporte1_Result>("buscarTransporte1");
        }
    
        public virtual ObjectResult<buscarCliente11_Result> buscarCliente11(string consulta)
        {
            var consultaParameter = consulta != null ?
                new ObjectParameter("consulta", consulta) :
                new ObjectParameter("consulta", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<buscarCliente11_Result>("buscarCliente11", consultaParameter);
        }
    
        public virtual ObjectResult<buscarRengCC_Result> buscarRengCC(string consulta)
        {
            var consultaParameter = consulta != null ?
                new ObjectParameter("consulta", consulta) :
                new ObjectParameter("consulta", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<buscarRengCC_Result>("buscarRengCC", consultaParameter);
        }
    
        public virtual ObjectResult<buscarRengCP_Result> buscarRengCP(string consulta)
        {
            var consultaParameter = consulta != null ?
                new ObjectParameter("consulta", consulta) :
                new ObjectParameter("consulta", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<buscarRengCP_Result>("buscarRengCP", consultaParameter);
        }
    
        public virtual ObjectResult<buscarRengCP1_Result> buscarRengCP1(string consulta)
        {
            var consultaParameter = consulta != null ?
                new ObjectParameter("consulta", consulta) :
                new ObjectParameter("consulta", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<buscarRengCP1_Result>("buscarRengCP1", consultaParameter);
        }
    
        public virtual ObjectResult<buscarPedidosActivos_Result> buscarPedidosActivos(string consulta)
        {
            var consultaParameter = consulta != null ?
                new ObjectParameter("consulta", consulta) :
                new ObjectParameter("consulta", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<buscarPedidosActivos_Result>("buscarPedidosActivos", consultaParameter);
        }
    
        public virtual ObjectResult<buscarRengPE_Result> buscarRengPE(string consulta)
        {
            var consultaParameter = consulta != null ?
                new ObjectParameter("consulta", consulta) :
                new ObjectParameter("consulta", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<buscarRengPE_Result>("buscarRengPE", consultaParameter);
        }
    
        public virtual ObjectResult<buscarRengPE2_Result> buscarRengPE2(string consulta)
        {
            var consultaParameter = consulta != null ?
                new ObjectParameter("consulta", consulta) :
                new ObjectParameter("consulta", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<buscarRengPE2_Result>("buscarRengPE2", consultaParameter);
        }
    }
}
