//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIS.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZCotizacionRengNB
    {
        public int reng_num { get; set; }
        public string doc_num { get; set; }
        public string co_art { get; set; }
        public decimal total_art { get; set; }
        public decimal prec_vta { get; set; }
        public int tipo_imp { get; set; }
        public decimal monto_imp { get; set; }
        public decimal reng_neto { get; set; }
    }
}
