//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIS.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZCotizacionNB
    {
        public string doc_num { get; set; }
        public string co_cli { get; set; }
        public string co_tran { get; set; }
        public string tip_cli { get; set; }
        public System.DateTime fec_emis { get; set; }
        public decimal total_bruto { get; set; }
        public decimal monto_imp { get; set; }
        public decimal total_neto { get; set; }
        public decimal tasa { get; set; }
    }
}
